spring:
  application:
    name: ext-app



# Now using H2 db, later change to mysql
#  datasource:
#    url: jdbc:mysql://localhost:3306/app_db
#    username: root
#    password: password
#    driver-class-name: com.mysql.cj.jdbc.Driver
#
#  jpa:
#    hibernate:
#      ddl-auto: update