spring:
  application:
    name: ext-app

    # Liquibase
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml


  datasource:
    url: jdbc:mysql://localhost:3306/ext-app
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

# TODO: could not put in application-dev.yml
  mail:
    host: sandbox.smtp.mailtrap.io
    port: 587
    username: ${MAILTRAP_USERNAME}
    password: ${MAILTRAP_PASSWORD}
    properties:
      mail:
        SMTP:
          auth: true
          STARTTLS:
            enabled: true

#  datasource:
#    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
#    driver-class-categoryName: org.h2.Driver
#    username: a
#    password:

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true


logging:
  level:
    liquibase: INFO

server:
  port: 8090

app:
  jwt:
    secret: change-me-in-production-environment
    refreshExpiration: 36000000 # 10 Hours
  frontend:
    password-reset-url: localhost:3000/password/reset
